src/Entity/Producto.php
<?php

namespace App\Entity;

use App\Repository\ProductoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductoRepository::class)]
class Producto
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $prd_nombre = null;

    #[ORM\Column(length: 255)]
    private ?string $prd_unidad = null;

    #[ORM\Column]
    private ?float $prd_precio = null;

    #[ORM\Column(nullable: true)]
    private ?float $prd_precio_unitario = null;

    #[ORM\Column]
    private ?float $prd_costo = null;

    #[ORM\Column]
    private ?float $prd_iva = null;

    #[ORM\Column]
    private ?int $prd_cantidad = null;

    #[ORM\ManyToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Proveedor $prov_codigo = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrdNombre(): ?string
    {
        return $this->prd_nombre;
    }

    public function setPrdNombre(string $prd_nombre): self
    {
        $this->prd_nombre = $prd_nombre;

        return $this;
    }

    public function getPrdUnidad(): ?string
    {
        return $this->prd_unidad;
    }

    public function setPrdUnidad(string $prd_unidad): self
    {
        $this->prd_unidad = $prd_unidad;

        return $this;
    }

    public function getPrdPrecio(): ?float
    {
        return $this->prd_precio;
    }

    public function setPrdPrecio(float $prd_precio): self
    {
        $this->prd_precio = $prd_precio;

        return $this;
    }

    public function getPrdPrecioUnitario(): ?float
    {
        return $this->prd_precio_unitario;
    }

    public function setPrdPrecioUnitario(?float $prd_precio_unitario): self
    {
        $this->prd_precio_unitario = $prd_precio_unitario;

        return $this;
    }

    public function getPrdCosto(): ?float
    {
        return $this->prd_costo;
    }

    public function setPrdCosto(float $prd_costo): self
    {
        $this->prd_costo = $prd_costo;

        return $this;
    }

    public function getPrdIva(): ?float
    {
        return $this->prd_iva;
    }

    public function setPrdIva(float $prd_iva): self
    {
        $this->prd_iva = $prd_iva;

        return $this;
    }

    public function getPrdCantidad(): ?int
    {
        return $this->prd_cantidad;
    }
    public function setPrdCantidad(int $prd_cantidad): self
    {
        $this->prd_cantidad = $prd_cantidad;

        return $this;
    }

    public function getProvCodigo(): ?Proveedor
    {
        return $this->prov_codigo;
    }
    public function getProvName(): ?string
    {
        return $this->prov_codigo->getProvNombre();
    }
    public function setProvCodigo(Proveedor $prov_codigo): self
    {
        $this->prov_codigo = $prov_codigo;

        return $this;
    }
}

src/Form/ProductoType.php
<?php

namespace App\Form;

use App\Entity\Producto;
use App\Entity\Proveedor;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('prd_nombre', null,['label' => 'Nombre', ])
            ->add('prd_unidad', null, ['label' => 'Unidad', ])
            ->add('prd_precio', null, ['label' => 'Precio', ])
            ->add('prd_precio_unitario', null, ['label' => 'Precio Unitario', ])
            ->add('prd_costo', null, ['label' => 'Costo', ])
            ->add('prd_iva', null, ['label' => 'IVA %', ])
            ->add('prd_cantidad', null, ['label' => 'Cantidad', ])
            ->add('prov_codigo', EntityType::class, ['class' => Proveedor::class, 'choice_label' => 'prov_nombre', 'label'=>'Proveedor'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Producto::class,
        ]);
    }
}

src/Controller/ProductoController.php
<?php

namespace App\Controller;

use App\Entity\Producto;
use App\Form\ProductoType;
use App\Repository\ProductoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/producto')]
class ProductoController extends AbstractController
{
    #[Route('/', name: 'app_producto_index', methods: ['GET'])]
    public function index(ProductoRepository $productoRepository): Response
    {
        return $this->render('producto/index.html.twig', [
            'productos' => $productoRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_producto_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ProductoRepository $productoRepository): Response
    {
        $producto = new Producto();
        $form = $this->createForm(ProductoType::class, $producto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $productoRepository->save($producto, true);

            return $this->redirectToRoute('app_producto_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('producto/new.html.twig', [
            'producto' => $producto,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_producto_show', methods: ['GET'])]
    public function show(Producto $producto): Response
    {
        return $this->render('producto/show.html.twig', [
            'producto' => $producto,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_producto_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Producto $producto, ProductoRepository $productoRepository): Response
    {
        $form = $this->createForm(ProductoType::class, $producto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $productoRepository->save($producto, true);

            return $this->redirectToRoute('app_producto_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('producto/edit.html.twig', [
            'producto' => $producto,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_producto_delete', methods: ['POST'])]
    public function delete(Request $request, Producto $producto, ProductoRepository $productoRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$producto->getId(), $request->request->get('_token'))) {
            $productoRepository->remove($producto, true);
        }

        return $this->redirectToRoute('app_producto_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/producto/_delete_form.html.twig
<form method="post" action="{{ path('app_producto_delete', {'id': producto.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ producto.id) }}">
    <button class="btn">Eliminar</button>
</form>

templates/producto/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}

templates/producto/edit.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{{ asset('CSS/styles_edit_producto.css') }}">
{% endblock %}

{% block title %}Edit Producto{% endblock %}

{% block body %}
    <nav class = "navbar">
        <div id="izquierda">
            <a href="{{ path('app_producto_index') }}">
                    <i class='bx bx-arrow-back'></i>
                    <span>Back</span>
            </a>  
            <div class="navbar-brand">Droguisalud</div>
        </div>
        {{ include('producto/_delete_form.html.twig') }}
    </nav>
    <div class="container">
        <h1 class = "titulo">Editar producto</h1>
        {{ include('producto/_form.html.twig', {'button_label': 'Actualizar'}) }}
    </div>
    
{% endblock %}

templates/producto/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="shortcut icon" href="src/Icons/icon.png">
    <link rel="stylesheet" href="{{ asset('CSS/styles_insert_producto.css') }}">
{% endblock %}

{% block title %}Producto index{% endblock %}

{% block body %}
    <nav clas = "navbar">
        <div class="navbar-brand">Droguisalud</div>
        <div class="buscar">
            <input type="text" id="busqueda" name = "busqueda"  required placeholder = "Buscar" class="serch">
            <input type="submit" value = "Buscar" class = "btn-create">
        </div>
        <a href="{{ path('app_producto_new') }}" class ="btn-create">Crear producto</a> 
    </nav>
    <div class="table-container">
        <div class="table-title">
            <h1 class = "titulo">Inventario</h1>
            <table class="table">
                <thead>
                    <tr>
                        <th class ="primero">Id</th>
                        <th>Nombre</th>
                        <th>Unidad</th>
                        <th>Precio</th>
                        <th>Precio Unitario</th>
                        <th>Costo</th>
                        <th>IVA %</th>
                        <th>Cantidad</th>
                        <th class ="ultimo">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                {% for producto in productos %}
                    <tr>
                        <td data-label="Id">{{ producto.id }}</td>
                        <td data-label="Nombre">{{ producto.prdNombre }}</td>
                        <td data-label="Unidad">{{ producto.prdUnidad }}</td>
                        <td data-label="Precio">{{ producto.prdPrecio }}</td>
                        <td data-label="Precio Unitario">{{ producto.prdPrecioUnitario }}</td>
                        <td data-label="Costo">{{ producto.prdCosto }}</td>
                        <td data-label="IVA">{{ producto.prdIva }}</td>
                        <td data-label="Cantidad">{{ producto.prdCantidad }}</td>
                        <td>
                            <a href="{{ path('app_producto_show', {'id': producto.id}) }}" class ="btn">Visualizar</a>
                            <a href="{{ path('app_producto_edit', {'id': producto.id}) }}" class = "btn">Editar</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="9">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>    
    </div>
        
{% endblock %}

templates/producto/new.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{{ asset('CSS/styles_new_producto.css') }}">
{% endblock %}
{% block title %}Nuevo Producto{% endblock %}

{% block body %}
    <nav clas = "navbar">
        <a href="{{ path('app_producto_index') }}">
            <i class='bx bx-arrow-back'></i>
            <span>Back</span>
        </a>
         <div class="navbar-brand">Droguisalud</div>
    </nav>
    <div class ="form-container">
        <h1 class ="titulo">Nuevo Producto</h1>

        {{ include('producto/_form.html.twig') }}
    </div>
{% endblock %}

templates/producto/show.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{{ asset('CSS/styles_show_product.css') }}">
{% endblock %}
{% block title %}Producto{% endblock %}

{% block body %}
    <nav clas = "navbar">
        <a href="{{ path('app_producto_index') }}">
            <i class='bx bx-arrow-back'></i>
            <span>Back</span>
        </a>
        <div class="navbar-brand">Droguisalud</div>
    </nav>
    
    <div class="table-container">
        <h1 class ="titulo">Producto</h1>
        <table class="table">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td  data-label= "Id">{{ producto.id }}</td>
                </tr>
                <tr>
                    <th>Nombre</th>
                    <td  data-label= "Nombre">{{ producto.prdNombre }}</td>
                </tr>
                <tr>
                    <th>Unidad</th>
                    <td  data-label= "Unidad">{{ producto.prdUnidad }}</td>
                </tr>
                <tr>
                    <th>Precio</th>
                    <td  data-label="Precio">{{ producto.prdPrecio }}</td>
                </tr>
                <tr>
                    <th>Precio Unitario</th>
                    <td  data-label="Precio Unitario">{{ producto.prdPrecioUnitario }}</td>
                </tr>
                <tr>
                    <th>Costo</th>
                    <td  data-label="Costo">{{ producto.prdCosto }}</td>
                </tr>
                <tr>
                    <th>IVA %</th>
                    <td  data-label="IVA %">{{ producto.prdIva }}</td>
                </tr>
                <tr>
                    <th>Cantidad</th>
                    <td  data-label="Cantidad">{{ producto.prdCantidad }}</td>
                </tr>
                <tr>
                    <th>Proveedor</th>
                    <td  data-label= "Proveedor">{{ producto.getProvName()}}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class = "btn-container">
        <a href="{{ path('app_producto_edit', {'id': producto.id}) }}" class = "btn-view">Editar</a>
        {{ include('producto/_delete_form.html.twig') }}
    </div>
{% endblock %}